<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P53AVDF" failures="2" tests="12" name="MyTests.FirstSeleniumScript" time="8.450" errors="0" timestamp="2024-05-28T16:18:22 EDT" skipped="2">
  <testcase classname="MyTests.FirstSeleniumScript" name="demo0" time="1.462"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.411"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.180"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="1.419">
    <skipped/>
  </testcase> <!-- demo1 -->
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="1.179">
    <failure message="expected [8] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8] but found [2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyTests.FirstSeleniumScript.demo1(FirstSeleniumScript.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- demo1 -->
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.131"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="1.167">
    <skipped/>
  </testcase> <!-- demo1 -->
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.824"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.490"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.257"/>
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="0.142">
    <failure message="expected [8] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8] but found [2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyTests.FirstSeleniumScript.demo1(FirstSeleniumScript.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- demo1 -->
  <system-out/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo0" time="0.788"/>
  <system-out/>
</testsuite> <!-- MyTests.FirstSeleniumScript -->
