<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P53AVDF" failures="1" tests="6" name="Parallel Tests chrome" time="3.83" errors="0" timestamp="2024-05-28T15:15:54 EDT">
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.002"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo0" time="0.158"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.001"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="0.453">
    <skipped/>
  </testcase> <!-- demo1 -->
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.001"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="0.045">
    <failure type="java.lang.AssertionError" message="expected [8] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [2]
at MyTests.FirstSeleniumScript.demo1(FirstSeleniumScript.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
</testsuite> <!-- Parallel Tests chrome -->
